---
abstract: 'Class for smart working with DB'
author:
  - 'Sergei Svistunov <sergei-svistunov@yandex.ru>'
build_requires:
  FindBin: '0'
  QBit::Application: '0'
  Test::Deep: '0'
  Test::More: '0'
  lib: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.043, CPAN::Meta::Converter version 2.143240'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: QBit-Application-Model-DBManager
requires:
  Exception: '0'
  Parse::Eyapp: '0'
  QBit::Application::Model: '0'
  QBit::Class: '0'
  base: '0'
  qbit: '0'
version: '0.021'
